#!/bin/bash
# installs yalalr externals, to go with git yalalr repo.   -cem bozsahin
#  also sets PATH and lisp execs so that yalalr is available from anywhere
yalalrdir=`pwd`
# brew does not allow sudo anymore.
SUDO=sudo    
echo 'yalalr external resources install and path set up'
echo '================================================='
# check to see if there is already a yalalr
if [ "$YALALR_HOME" ]; then
  echo "You have a yalalr system installed at $YALALR_HOME."
  echo "Just go there and do 'git pull' for updates"
  exit -1
fi
# check to see if lalr parser has been installed before
if [ ! "$LALR_HOME" ]; then
  wget -v --no-check-certificate --backups=3 http://web.science.mq.edu.au/~mjohnson/code/lalrparser.lisp
  lalr=`pwd`
else
  echo "lalrparser.lisp found at $LALR_HOME. Using it"
  lalr=$LALR_HOME
fi
# check to see if a Lisp has been installed before
if [ -x /usr/local/bin/sbcl ] || [ -x /usr/bin/sbcl ] || [ -x /usr/local/bin/ccl ] || [ -x /usr/bin/ccl ]; then
  locallisp=`which sbcl` || `which ccl`   # default is sbcl
fi
if [ -x "$locallisp" ]; then 
  echo 'got it.'
else
  echo 'no local SBCL, CCL or other Lisp set.'
  echo '! Set the YALALR_LISP variable in .bashrc to your binary later if I cannot install SBCL below'
  unset locallisp
fi
#check if lisp needs installing
if [ ! "$locallisp" ]; then
  if [ -x /usr/bin/yum ] || [ -x /usr/local/bin/yum ]; then
        packager=yum
	# open library space of yum
	$SUDO yum install yum-utils
	$SUDO yum-config-manager --enable \*
  fi
  if [ -x /usr/local/bin/brew ] || [ -x /sw/bin/brew ] || [ -x /sw/local/bin/brew ]; then
    	packager=brew
	SUDO=
  fi
  if [ -x /usr/bin/apt-get ] || [ -x /usr/local/bin/apt-get ]; then
	packager=apt-get   # overrides brew if you have them both
	$SUDO add-apt-repository universe
	$SUDO apt-get update
  fi
  if [ "$packager" ]; then
	echo '! WARNING: you need sudo access now'
	$SUDO $packager install sbcl
	locallisp=`which sbcl`
	if [ -x /usr/local/bin/rlwrap ] || [ -x /usr/bin/rlwrap ] || [ -x /sw/bin/rlwrap ] || [ -x /sw/local/bin/rlwrap ]; then
		echo 'Using local rlwrap'
	else 
		echo 'rlwrap not found. It is very annoying NOT to have it when you run yalalr'
		echo 'WARNING: you need sudo access now'
		$SUDO $packager install rlwrap
        fi
  else
	echo 'apt-get, yum or brew not found. I leave Common Lisp and rlwrap handling to you.'
  fi
else
  echo "Using the Lisp at $locallisp for yalalr"
fi
printf '%s\n' '# stuff added by yalalr installer' >> ~/.bashrc
if [ -x /usr/local/bin/rlwrap ] || [ -x /usr/bin/rlwrap ] || [ -x /sw/bin/rlwrap ] || [ -x /sw/local/bin/rlwrap ]; then
  if [ ! "$RLWRAP" ]; then
    printf '%s\n' 'export RLWRAP=rlwrap' >> ~/.bashrc
  fi
else
  printf '%s\n' 'export RLWRAP=' >> ~/.bashrc
  echo '! If rlwrap is installed later, change the RLWRAP variable in ~/.bashrc'
fi
printf '%s\n%s\n%s\n%s\n' "export YALALR_HOME=$yalalrdir" "export YALALR_LISP=$locallisp" "export LALR_HOME=$lalr" "export PATH=:.:\$YALALR_HOME/bin:\$PATH" >> ~/.bashrc
printf '%s\n' '# end of stuff added by yalalr installer' >> ~/.bashrc
printf '%s\n' '# stuff added by yalalr installer' >> ~/.bash_profile
printf '%s\n' 'if [ -f ~/.bashrc ]; then source ~/.bashrc; fi' >> ~/.bash_profile
echo 'install: completed.'
echo 'To run, first open a fresh terminal, or logout and login. Then do'
echo 'yalalr'
echo '================================================='
